### python basics



In [5]:
a=10
b=10.5
print(a)
print(b)
print(type(a))
print(type(b))

10
10.5
<class 'int'>
<class 'float'>


In [2]:
b=100


In [6]:
print(type(b))

<class 'float'>


In [7]:
c=10+5j
print(type(c))

<class 'complex'>


## Working with input

In [8]:
name=input("Enter your name")
print("Hello")
print(name)

Enter your nameMannika
Hello
Mannika


In [9]:
name=input("Enter your name")
print("Hello",end=" ")
print(name)

Enter your nameMannika
Hello Mannika


## Reading numbers-Type casting

In [10]:
#a=input("Enter a number")
#print("Square of the number is"+a*a)
#this gives an error:-can't multiply sequence by non-int of type 'str'


Enter a number5


TypeError: can't multiply sequence by non-int of type 'str'

In [11]:
print(type(a))

<class 'str'>


In [12]:
a=int(a)

In [13]:
print("Square of the number is"+a*a)

TypeError: can only concatenate str (not "int") to str

In [15]:
a=int(input("Enter a number"))
print("Square of the number is:"+str(a*a))

Enter a number5
Square of the number is:25


## print
    - sep
    - end
    - format

In [16]:
print("Mannika","Garg","is","the","best")

Mannika Garg is the best


In [17]:
print("Mannika","Garg","is","the","best",sep=",,")

Mannika,,Garg,,is,,the,,best


In [24]:
print("Mannika","Garg","is","the","best",sep="\n")

Mannika
Garg
is
the
best


In [25]:
a=10
print(a,end=" and ")
b=20
print(b)


10 and 20


In [26]:
a="indians"
b="mango"
c="pakistanis"
d="bananas"


In [32]:
print("{0} love {1}" .format(c,d))

pakistanis love bananas


In [33]:
print("%s love %s" %(a,b))

indians love mango


## precision in float


In [37]:
#for precision upto 4 decimal places
a=7
b=3
print("%0.4f"%(a/b))

2.3333


## multiple variable assignment

In [38]:
a,b,c=10,4.5,"hello"

In [39]:
print(a,b,c)

10 4.5 hello


In [1]:
y=6
a=2*y+5
print(a)

17


In [2]:
a=int(input("Enter a number:"))

if a<0:
    print(-1)
elif a==0:
    print(0)
else:
    print(1)
    

Enter a number:-5
-1


## Loops in python


In [2]:
n=10
i=1

while(i<=10):
    print("Step %d"%i)
    i+=1   #python does not have i++ functionality
    #i++
print("Loop ended")

Step 1
Step 2
Step 3
Step 4
Step 5
Step 6
Step 7
Step 8
Step 9
Step 10
Loop ended


In [ ]:
i=1

for j in range(1,11):
    i*=j
print(i)

In [11]:
for i in range(5):
    for j in range(5):
        print(5+3,end=" ")
    print(" ")
        

8 8 8 8 8  
8 8 8 8 8  
8 8 8 8 8  
8 8 8 8 8  
8 8 8 8 8  


## Break continue and pass statements

In [3]:
 for i in range(10):
        if i==5:
            break;
        print(i,end=" ")

0 1 2 3 4 

In [4]:
 for i in range(10):
        if i==5:
            continue;
        print(i,end=" ")

0 1 2 3 4 6 7 8 9 

In [13]:
 for i in range(10):
        if i==5:
            pass;
        print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 

In [2]:
#printing pprime numbers
import math
prime=True; 
for i in range(3,21):
    prime=True
    for j in range(2,math.floor(i/2)+1):
        if i%j==0:
            prime=False
    if prime==True:
        print(i,end=" ")

3 5 7 11 13 17 19 

## Default argument values & local Global Variables

In [4]:
def say(x="Python"):
    print("I love %s"%x)
say("Javascript")
say()

I love Javascript
I love Python


##  Recursive Funtion

In [5]:
def fact(n):
    if n<=1:
        return 1
    else:
        return(n*fact(n-1))
fact(4)

24

## Quick sort

In [1]:
def q_sort(x[]):
    

SyntaxError: invalid syntax (<ipython-input-1-cadad01d1267>, line 1)

### Strings

In [10]:
a="Mannika"
print(a[2])
print(a[1:-2]) 
print(a[-1])

n
anni
a


In [11]:
print(len(a))

7


In [16]:
b="is the best"
print(a+" "+b)
print(a*5)


Mannika is the best
MannikaMannikaMannikaMannikaMannika


## Iterate the string

In [13]:
for i in range(len(a)):
    print(a[i])

M
a
n
n
i
k
a


In [15]:
for c in a:
    print(c)
    

M
a
n
n
i
k
a


## Range slicing


In [22]:
print(a[2:])
print(a[1:6])
print(a[1:-2])
print(a[-1:8])

nnika
annik
anni
a


### Membership: Substring is present in bigger string

In [24]:
a="Mango"
"go" in a

True

### String formating

In [32]:
print("%s is the %s" %("Mannika","best"))

Mannika is the best


In [35]:
a="""Mannika
is the best"""
print(a)

Mannika
is the best


In [36]:
a="Mango is a fruit"
l=a.split()
print(l)
print(type(l))
print(type(l[0]))

['Mango', 'is', 'a', 'fruit']
<class 'list'>
<class 'str'>


In [37]:
b="""How are
you man?
are you fine?"""

l=b.splitlines()
print(l)
print(b.upper())

['How are', 'you man?', 'are you fine?']
HOW ARE
YOU MAN?
ARE YOU FINE?


### DATA STRUCTURS IN PYTHON
    1.Strings
    2.Lists
    3.Tuples
    4.Dictionaries 
    4.Set

##### Lists-->Like arrays, heterogeneous lists

In [14]:
my_list=[1,2,3,"Mannika"]
print(my_list)
print(type(my_list))

[1, 2, 3, 'Mannika']
<class 'list'>


In [29]:
l1=[1,2,3]
l2=l1
l2=l1+l2
print(l2)
print(l1)


[1, 2, 3, 1, 2, 3]
[1, 2, 3]


In [30]:
l3=[4,5,6]
l1.extend(l3)    #you can also use extend instead of + for concatination
print(l1)

[1, 2, 3, 4, 5, 6]


In [2]:
#list of square numbers from 1 to 5
l=[n*n for n in range(1,6)]
print(l)

[1, 4, 9, 16, 25]


## Insersetion and deletion in a list
  1. append                
  2. insert
  3. remove
  4. del
  5. pop

In [14]:
l1=[1,2,3]
l2=[4,5]
l2.append(6)
print(l2)

[4, 5, 6]


In [15]:
l1.append(l2)
print(l1)

[1, 2, 3, [4, 5, 6]]


In [16]:
print(l1[3][1])

5


In [17]:
##INSERT
l1.insert(4,7)
print(l1)

[1, 2, 3, [4, 5, 6], 7]


In [18]:
##REMOVE--> removes the element you want to delete
l1.remove(8)

ValueError: list.remove(x): x not in list

In [19]:
l1.remove(3)
print(l1)

[1, 2, [4, 5, 6], 7]


In [23]:
##DEL --> index wise deletion
del l1[2]
print(l1)


[1, 2, 7]


In [24]:
##POP
l1.pop()
print(l1)

[1, 2]


In [26]:
print(l1*2)

[1, 2, 1, 2]


In [28]:
2 in l1


True

### Serching and sorting a list

In [38]:
#linear search
l=[4,3,24,76,87,2,1]
print(l.index(24))

2


In [39]:
max(l)

87

In [40]:
min(l)

1

In [41]:
#sorting
print(sorted(l)) #does not change the original list
print(l)
l=sorted(l)
print(l)


[1, 2, 3, 4, 24, 76, 87]
[4, 3, 24, 76, 87, 2, 1]
[1, 2, 3, 4, 24, 76, 87]


In [42]:
l=[4, 3, 24, 76, 87, 2, 1]
l.sort()
print(l)

[1, 2, 3, 4, 24, 76, 87]


In [44]:
l.sort(reverse=True)
print(l)

[87, 76, 24, 4, 3, 2, 1]


In [45]:
num=input().split()
print(num)
print(type(num))
print(type(num[1]))

1 2 3 4
['1', '2', '3', '4']
<class 'list'>
<class 'str'>


In [46]:
num=[int(n) for n in input().split()]
print(num)
print(type(num))
print(type(num[1]))

1 2 3 4 
[1, 2, 3, 4]
<class 'list'>
<class 'int'>


# DICTIONARY
    1. store info in key, value pair
    2. lookup value for any key, key unique
    3. key values are not stored in any order
    

In [47]:
d={}
print(type(d))

<class 'dict'>


In [48]:
d={"mango":100,"orange":180,"grape":90}
print(d)
print(d["mango"])

{'mango': 100, 'orange': 180, 'grape': 90}
100


In [50]:
## Adding new element
d["guava"]=70.9
print(d)

{'mango': 100, 'orange': 180, 'grape': 90, 'guava': 70.9}


In [52]:
d["pineapple"]={"small":30,"large":90}
print(d["pineapple"])
print(d["pineapple"]["small"])

{'small': 30, 'large': 90}
30


In [55]:
print(d.keys())

dict_keys(['mango', 'orange', 'grape', 'guava', 'pineapple'])


In [56]:
print(d.values())

dict_values([100, 180, 90, 70.9, {'small': 30, 'large': 90}])


### Some common dictionary methods and operations
1. get()
2. items()
3. keys()
4. values()
5. clear()
6. update()
7. in, not in
8. del

In [57]:
print(d["lol"])

KeyError: 'lol'

In [59]:
## get --> get value of the given key
print(d.get("lol"))
print(type(d.get("lol")))

None
<class 'NoneType'>


In [69]:
fruit=input("Enter a fruit: ")
if fruit in d:
    print("price of %s is %d" %(fruit,d.get(fruit)))
else:
    print("%s not available" %(fruit.capitalize()))
          

Enter a fruit: apple
Apple not available


In [70]:
## keys() and values() returns a list of keys and values
## items returns a list of tupple(key value pair in case of dictionary)

print(d.items())
print(type(d.items()))

dict_items([('mango', 100), ('orange', 180), ('grape', 90), ('guava', 70.9), ('pineapple', {'small': 30, 'large': 90})])
<class 'dict_items'>


In [71]:
l=list(d.items())
print(l)

[('mango', 100), ('orange', 180), ('grape', 90), ('guava', 70.9), ('pineapple', {'small': 30, 'large': 90})]


In [72]:
del d["mango"]

In [73]:
print(d)

{'orange': 180, 'grape': 90, 'guava': 70.9, 'pineapple': {'small': 30, 'large': 90}}


In [74]:
## update
d2={"strawberry":95}
d.update(d2)
print(d)

{'orange': 180, 'grape': 90, 'guava': 70.9, 'pineapple': {'small': 30, 'large': 90}, 'strawberry': 95}


In [75]:
## len
print(len(d))

5


In [77]:
## clear
d.clear()
print(len(d))

0


In [78]:
## dictionary to list -->items

## lists to dictionary

## Working with Numpy- for mathematical operations 

In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)  #returns a tuple which is dimension of array. a is 1d array. a[]

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
b=np.array([[1],[2],[3],[4],[5]])
print(b.shape)   #2d array. b[][]

(5, 1)


In [7]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [17]:
# create zeros, ones,custom array
a=np.zeros((3,3))
print(a)

b=np.ones((2,3))
print(b)

#Array of some constants
c= np.full((3,2),5)
print(c)

#Identity Mtrix - Size/Square matrix
d= np.eye(4)
print(d)

#Random Matrix
randomMatrix= np.random.random((2,3))
print("")
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0.44434958 0.01678858 0.69934287]
 [0.08872321 0.70585123 0.44581849]]


In [18]:
print(randomMatrix[:,1])

[0.01678858 0.70585123]


In [19]:
randomMatrix[1,1:]=1  #slicing
print(randomMatrix)

[[0.44434958 0.01678858 0.69934287]
 [0.08872321 1.         1.        ]]


In [20]:
## Set some rows and columns with any values
z=np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1]=7
print(z)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [22]:
# Datatypes
print(z.dtype)

#converting to int
z=np.zeros((3,3),dtype=np.int64)
print(z.dtype)

float64
int64


In [25]:
#Mathematical operations

x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

#Element Wise Addition
print(x+y)
    #or
print(np.add(x,y))

#Element Wise Subtraction
print(x-y)
    #or
print(np.subtract(x,y))

#Element Wise Multiplication
print(x*y)
    #or
print(np.multipy(x,y))

#Element Wise Addition
print(x+y)
    #or
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
